### PR TITLE
Oracle Reports are stored in an array, not a map

### PR DESCRIPTION
**Pull request by dechjo**
Change `EpochData.reports` form `mapping (uint256 => Report) reports` to `Report[] reports`.

### CODE REVIEW

**Comment by dechjo** [comment]
My concerns here:
1. What length should be `EpochData.reports` array? I think this should be 
   - `0` if the epoch is yet untouched and 
   - `MAX_MEMBERS` if it was ever reported. 
   I think that keeping the actual size for this array is actually redundant.

2. I did not modify the `Algorithm` code and left creating in-memory array for it intact. Because the number of oracles is limited and it should not take a lot of gas while leaving the Algorithms's code clear. 

Let me know if you think of better improvements.

**Comment by vshvsh** [comment]
You can make the whole thing a lot simpler by storing report aggregate counts instead of individual reports.

```
    struct Report {
        uint128 beaconBalance;
        uint128 beaconValidators;
        uint256 reportsCount; //taking whole slot anyway
    }

...

        epochData.reportsBitMask = bitMask.setBit(index, true);
        //if there was a report like that return its positon or return -1
        reportsPosition = findReportInArray(epochData.reports, _beaconBalance, _beaconValidators); 
        if (reportPosition>=0) {
          epochData.reports[reportPosition].reportsCount += 1;
       } 
       else {
            addReportToArray(epochData.reports, _beaconBalance, _beaconValidators, 1)
       }
```
If you do it like that quorum calc is trivial (just find biggest reportCount and compare to the quorum).

**Comment by dechjo** [comment]
But then we will not be able to `removeOracleMember` without invalidating all epochs already reported, is it fine? I mean that currently when we remove some member, we also invalidate its vote on the last epoch because we track vote-member relationship.

**Comment by vshvsh** [comment]
Good catch! it's fine as long the remaining oracles can resubmit the same epoch immediately.
e.g. we clear reports and bitmask but do not change a reportable epoch

**Comment by dechjo** [comment]
Ok, I have reviewed the Oracle daemon code and it looks that currently, it re-submits the (same) data every `SLEEP` interval (1 hour, if configured as in README). Is it OK or should we also update this logic?

**Comment by vshvsh** [comment]
It tries to resubmit and fails (before sending a tx) if their report is already submitted or the frame is already successfully reported.

**Comment by dechjo** [comment]
Right, but they resubmit not earlier than in an hour. Is it OK, or should we add some logic that tracks, say, some event and resubmits immediately?

**Comment by vshvsh** [comment]
1h is okay. With the new release we can actually make that interval about 5m in practice

**Comment by dechjo** [comment]
Replaced by https://github.com/lidofinance/lido-dao/pull/296.

**Pull request closed without merging**
